# For NodeJS Environment
name: CICD - NodeJS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # name: Build & Test on Node.js ${{ matrix.node_version }} and ${{ matrix.os }}
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     node_version: ['lts/*']
    #     os: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node_version: 'lts/*'
          # node_version: ${{ matrix.node_version }}
      
      - name: yarn install --frozen-lockfile
        run: yarn --frozen-lockfile

      # - name: yarn lint
      #   run: yarn lint

      # - name: yarn test --coverage
      #   run: yarn test --coverage

      - name: yarn build
        run: yarn build

      # # Available to merge above yarn commands.
      # - name: yarn install, build and test
      #   run: |
      #     yarn --frozen-lockfile
      #     yarn lint
      #     yarn test --coverage
      #     yarn build

      # # Upload & Download Artifact Jobs (Upload)
      # - name: Upload artifact for deployment job
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: node-app
      #     path: helloworld.zip

      - name: Set current date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d_%H:%M:%S')" >> $GITHUB_ENV

      - name: Zip artifact for deployment
        run: zip helloworld-$CURRENT_DATE.zip -r ./package* ./yarn.lock ./dist

      - name: Deploy to VM instance & Restart Apps
        env:
          VM_SSH_ADDR: azureuser@20.55.199.98
          UPLOAD_PATH: /home/azureuser/medly
          PEM_KEY: ${{ secrets.AZURE_VM_PEM }}
          PEM_KEY_FILE: 3rd-prj-team3-eastus2-vm.pem
        run: |
          echo "$PEM_KEY" >> $HOME/$PEM_KEY_FILE
          chmod 400 $HOME/$PEM_KEY_FILE

          ssh -i $HOME/$PEM_KEY_FILE -o StrictHostKeyChecking=no $VM_SSH_ADDR "sudo systemctl stop medly.service; rm -rf $UPLOAD_PATH/*"
          scp -i $HOME/$PEM_KEY_FILE -o StrictHostKeyChecking=no -r ./helloworld-$CURRENT_DATE.zip azureuser@20.55.199.98:$UPLOAD_PATH/
          ssh -i $HOME/$PEM_KEY_FILE -o StrictHostKeyChecking=no $VM_SSH_ADDR "unzip $UPLOAD_PATH/helloworld-$CURRENT_DATE.zip -d $UPLOAD_PATH; sudo systemctl start medly; sudo systemctl restart nginx"

      # Samples
      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.



  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     # Upload & Download Artifact Jobs (Download)
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: node-app
      
  #     - name: Set current date
  #       run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

  #     - name: Deploy to VM instance
  #       env:
  #         PEM_KEY: ${{ secrets.AZURE_VM_PEM }}
  #         PEM_KEY_FILE: 3rd-prj-team3-eastus2-vm.pem
  #       run: |
  #         echo "$PEM_KEY" >> $HOME/$PEM_KEY_FILE
  #         chmod 400 $HOME/$PEM_KEY_FILE
          
  #         scp -i $HOME/$PEM_KEY_FILE -o StrictHostKeyChecking=no -r ./* azureuser@20.55.199.98:/home/azureuser/GithubActions/
          
          
